version: "3"
services:
    db:
        image: "postgres"
        container_name: "profile_site_postgres"
        environment:
            - POSTGRE_USER=admin
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=profile_site_db
        ports:
            - "54320:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
